### ISSUE TITLE
wherre's 'make client' in da roadmap

### ISSUE THREAD

**Issue by SK-Fast** [TENEIDAE/Roblox-Clone-Tutorial#2]
making sandbox site without client frrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by stampe99** [comment]
Frr pixel man > blender 3d man

**Comment by ghost** [comment]
fr

**Comment by Kqpa** [comment]
# How to make a sandbox game client
ROBLOX clones have gotten pretty popular in the last years. Leading to many people wanting to know: How do I make one?

Lets start easy: **You're asking yourself how to basically make Roblox. Expect it to be kind of hard to make.**

## First of all we want to know what we need to know:
You cant make a ROBLOX clone overnight. You need a stable income from external sources. ROBLOX clones are not profitable. Only ROBLOX or very big clones, such as Brick-Hill, can use their very own income as payment. ROBLOX clones do not last.

Alright, now let's get to the steps:

# Step One
- Power off your computer.

Hope this helps @SK-Fast,
—  Kqpa

**Comment by stampe99** [comment]
muchos gracias dolaris for idiotas

**Comment by SK-Fast** [comment]
> # How to make a sandbox game client
> ROBLOX clones have gotten pretty popular in the last years. Leading to many people wanting to know: How do I make one?
> 
> Lets start easy: **You're asking yourself how to basically make Roblox. Expect it to be kind of hard to make.**
> 
> ## First of all we want to know what we need to know:
> You cant make a ROBLOX clone overnight. You need a stable income from external sources. ROBLOX clones are not profitable. Only ROBLOX or very big clones, such as Brick-Hill, can use their very own income as payment. ROBLOX clones do not last.
> 
> Alright, now let's get to the steps:
> 
> # Step One
> - Power off your computer.
> 
> Hope this helps @SK-Fast,
> —  Kqpa

So useful.....

**Comment by 10allday** [comment]
> # How to make a sandbox game client
> ROBLOX clones have gotten pretty popular in the last years. Leading to many people wanting to know: How do I make one?
> 
> Lets start easy: **You're asking yourself how to basically make Roblox. Expect it to be kind of hard to make.**
> 
> ## First of all we want to know what we need to know:
> You cant make a ROBLOX clone overnight. You need a stable income from external sources. ROBLOX clones are not profitable. Only ROBLOX or very big clones, such as Brick-Hill, can use their very own income as payment. ROBLOX clones do not last.
> 
> Alright, now let's get to the steps:
> 
> # Step One
> * Power off your computer.
> 
> Hope this helps @SK-Fast, — Kqpa

This is unrelated to the question.

**Comment by ghost** [comment]
wdym?!!!!! it perfectly tells you how

**Comment by 10allday** [comment]
@SK-Fast
Check out: https://github.com/openblox
